### ISSUE TITLE
Character Prefab skeleton in German

### ISSUE THREAD

**Issue by gustavoeb** [sebastianstarke/AI4Animation#10]
Hey, minor issue. The skeleton for the wolf character is in German (not in the demoscene, but in the project's assets). And some joint names seem to be hardcoded in English, like "Hip" in Frame.cs.

**Comment by sebastianstarke** [comment]
Yeah that's true - I did not create the wolf character myself so I have no "control" over this. I just re-rigged the model based on our mocap skeleton - that's all :) The "Hip" in Frame.cs should simply denote the root joint - you could also exchange this by "Bones[0]" probably. However, there might be several heuristics how to calculate the forward direction of the motion, which also affects the quality in motion learning.

**Comment by sebastianstarke** [comment]
Yeah that's true - I did not create the wolf character myself so I have no "control" over this. I just re-rigged the model based on our mocap skeleton - that's all :) The "Hip" in Frame.cs should simply denote the root joint - you could also exchange this by "Bones[0]" probably. However, there might be several heuristics how to calculate the forward direction of the motion, which also affects the quality in learning the motion.

**Comment by floodsung** [comment]
@sebastianstarke hi, how to re-rig the model ? I tried but failed. Could you share your approach? thank you
