### ISSUE TITLE
importing training data in unity AI4Animation 2022

### ISSUE THREAD

**Issue by kotaxyz** [sebastianstarke/AI4Animation#101]
i finished training my dataset but i have no clue how to import it using the deep phase importer in unity 

![zz](https://user-images.githubusercontent.com/105466290/218346861-b8c958b4-75de-4573-85f7-63f7276dd487.png)
![zxz](https://user-images.githubusercontent.com/105466290/218346923-172267f0-957f-4e52-b644-70f40ede677c.png)

**Comment by sebastianstarke** [comment]
You would need to assign the path to the sequence file that was generated when exporting your dataset from Unity for training the PAE and also the path to the phase file that was generated by PAE (Parameters_10.txt). After that, when you click process the script will add all the phases in the txt file to the associated frames in the asset files.
