### ISSUE TITLE
How to apply deepphase to music-dance generation?

### ISSUE THREAD

**Issue by youngstu** [sebastianstarke/AI4Animation#103]
How to apply deepphase to music to dance generation? 
And how to combine deepphase with FACT and Bailando. Could you provide some demo code. 

Very Thanks.

**Comment by youngstu** [comment]
How to encode a single frame without time range using deepphase in autoregressive decoder module?

**Comment by sebastianstarke** [comment]
For generating music features, this has been addressed here: https://github.com/sebastianstarke/AI4Animation/issues/97
For training the PAE decoder, the time range is needed to reconstruct the latent space from the learned phase parameters.

**Comment by starryforest-ymxk** [comment]
I just did some work on this. If you still have this question, you can find it here : [DeepPhase-DanceGeneration](https://github.com/starryforest-ymxk/DeepPhase-DanceGeneration) Hope it help you. :) @youngstu
