### ISSUE TITLE
train human characters 

### ISSUE THREAD

**Issue by kotaxyz** [sebastianstarke/AI4Animation#104]
hello there im struggling trainning my humanoid characters i was able to train quadrupeds but when trying to train human data it gives error note that i use the deep phase pipeline for this, the steps i did was ,creating new scene, importing mocap data ,importing my character with same skeleton as on the mocap data with the same bone naming with the same number of joints , i made new scene and created the same arranging for the character setup as on quadraped one , when trying to import bvh using motion editor ,the mesh disappers ,also it dont create the moduls for them

![sasd](https://user-images.githubusercontent.com/105466290/219273916-75d2abfe-38fc-43ed-9978-035f5558eefa.png)

**Comment by kotaxyz** [comment]
i added the moduls manually for everymotion and the train processed but still dont know how to avoid that mesh disapper problem

**Comment by sebastianstarke** [comment]
When training your own models, your character topology and joint names and others will likely change and you will have to build your own pipelines and setups with the framework. Also, this is an animation research repository and posts should mainly be regarding reproducibility of published works.

**Comment by trivikramak** [comment]
Hi Sebastian,

First of all, thanks for the amazing work!
Is there any implementation available for the human-body pipeline? 
Any documentation related to building a custom pipeline would also be helpful.

Best,

**Comment by cjerry1243** [comment]
I am also interested in using DeepPhase for humanoid characters. 
@kotaxyz @trivikramak Have you got any progress with it?

**Comment by starryforest-ymxk** [comment]
Hi, i wrote a custom human-body pipeline in [DeepPhase-DanceGeneration](https://github.com/starryforest-ymxk/DeepPhase-DanceGeneration) , but it is for dance generation. Hope it can help you. @cjerry1243 @trivikramak
