### ISSUE TITLE
reconstruction loss is high

### ISSUE THREAD

**Issue by kotaxyz** [sebastianstarke/AI4Animation#105]
reconstruction loss started arround 38 and it's getting less and less but still is high ,does it related with the coverage of the mocap data to surrounding areas i mean the more area my mocap covers the better, lets get to my question ,does this happen because i didnt give it so much mocap data or is it related to other setting 
![data](https://user-images.githubusercontent.com/105466290/219301048-ddb65c79-c2e6-4ec1-b68a-30de427bf762.png)

**Comment by sebastianstarke** [comment]
Looks good to me, nothing to worry about. You could give it more data, but often there seems no clear correspondence between training error and fitting quality in motion.
