### ISSUE TITLE
How to train PAE?

### ISSUE THREAD

**Issue by atodniAr** [sebastianstarke/AI4Animation#106]
Hi, thanks for amazing work.

I'm trying to train PAE on both your example data and some of other datasets I collected. In the README file it seems there was a `Train.py`: 

> The 'Dataset' folder contains a small subset of human dancing movements, and
the 'PAE' folder contains the network file. You can simply run the model after
installing the requirements via the command below (Anaconda is recommended):
>
> python Train.py

But I cound't find the `Train.py` file anywhere under PAE folder. Any help is appreciated :)

**Comment by pauzii** [comment]
Hi there, sorry for the confusion - the README file is now updated. Please run  `Network.py` in the PAE folder to start training. We just uploaded a tutorial that shows how to use the frameworks pipeline to train a motion controller with the learned phases. Hope it helps: https://www.youtube.com/watch?v=3ASGrxNDd0k

**Comment by trivikramak** [comment]
Hi Paul,

Thanks for the amazing work and the video explaining how to train the PAE and use it in-detail!
Is there any implementation available to generate PAE parameters using the human-body MoCAP data?
Any documentation related to building a custom pipeline for human-body MoCAP would also be helpful.

Best,

**Comment by GuangtaoLyu** [comment]
> Hi there, sorry for the confusion - the README file is now updated. Please run `Network.py` in the PAE folder to start training. We just uploaded a tutorial that shows how to use the frameworks pipeline to train a motion controller with the learned phases. Hope it helps: https://www.youtube.com/watch?v=3ASGrxNDd0k

how to use the PAE? I trained it. But i don't know how to use it?

**Comment by starryforest-ymxk** [comment]
Hi, i wrote a custom human-body pipeline in [DeepPhase-DanceGeneration](https://github.com/starryforest-ymxk/DeepPhase-DanceGeneration) , but it is for dance generation. Hope it can help you.
