### ISSUE TITLE
2018 broken links

### ISSUE THREAD

**Issue by Georgedf1** [sebastianstarke/AI4Animation#114]
Seems like many of the 2018 links, such as to the dog dataset, do not work (likely due to the www.starke-consult.de domain being used by someone else?).
Is there anywhere else I can access this dataset? or could you look into fixing the link and hosting so I can properly use the dataset in my own research?

Best,
George

**Comment by Georgedf1** [comment]
Noticed that https://starke-consult.de/paul/portfolio/ does point to a somewhat relevant site.

**Comment by pauzii** [comment]
Hi George, thanks for pointing this out. The hyperlinks in the readme's should work properly now. Could you try again please?

**Comment by Georgedf1** [comment]
Works now, thank you very much!
