### ISSUE TITLE
The hyperlink to the NSM dataset appears to be broken

### ISSUE THREAD

**Issue by Bin-Ji** [sebastianstarke/AI4Animation#120]
Hi, thanks for your great work.
I've encountered an issue with the link ```https://www.starke-consult.de/AI4Animation/SIGGRAPH_Asia_2019/MotionCapture.zip``` , and it appears to be inactive at the moment. Could you please provide an alternative source where I can obtain access to this dataset? Thank you.

**Comment by pauzii** [comment]
Hi Bin-Ji! Links should be working now. Please try again.
Thank you.

**Comment by Bin-Ji** [comment]
Appreciate your help!
