### ISSUE TITLE
Does the VR Demo - Three Point Tracking And Hybrid Mode run on anything other than PC/link cable?

### ISSUE THREAD

**Issue by keithahern** [sebastianstarke/AI4Animation#128]
Hello,

Very impressed with your 2024 SIGGRAPH project. 

From your instructions:
"Connect your VR device with a link-cable to your machine. For Quest and Windows you'll need the Quest desktop app to access link mode."

Does the VR demo require a PC and link cable?  Can it run standalone and/or connect to a mac? 

Thank you

**Comment by paulstarke** [comment]
There is now a VR-demo .APK that you can install on your headset without the need of link-cable.
