### ISSUE TITLE
VR Demo head / player movement

### ISSUE THREAD

**Issue by qlee01** [sebastianstarke/AI4Animation#130]
Nice work on the 2024 stuff. One thing I noticed though is that the algorithm enforces some artificial movements on the player location in many situations, which might lead to motion sickness. A mode where movement is only governed by the HMD would be preferable, and only do locomotion of player transform if stick is being used. 

Also would like to second the question about licensing for commercial use.

**Comment by paulstarke** [comment]
Hi @qlee01, in the VR demo you should be able to control the character with HMD and only when using the joystick the system will apply additional movement. Which device are you using?

**Comment by qlee01** [comment]
> Hi @qlee01, in the VR demo you should be able to control the character with HMD and only when using the joystick the system will apply additional movement. Which device are you using?

I am using quest 3 over meta link. Per default, no camera was rendering to the HMD, so I tried all three cameras by switching them to display 1 and setting output to both eyes. On all of them I saw additional movement, also visible on the parent transforms of the cameras in the editor.

**Comment by P3t3r95** [comment]
I echo what @qlee01 said, nice work! Any comments about the licensing for commercial use? 🤞

**Comment by paulstarke** [comment]
> > Hi @qlee01, in the VR demo you should be able to control the character with HMD and only when using the joystick the system will apply additional movement. Which device are you using?
> 
> I am using quest 3 over meta link. Per default, no camera was rendering to the HMD, so I tried all three cameras by switching them to display 1 and setting output to both eyes. On all of them I saw additional movement, also visible on the parent transforms of the cameras in the editor.

Hi @qlee01, I just tested on Quest 3 successfully. Please double check the following camera settings in the 3PT scene:

**ScreenSpace Camera**
- Target Display: 1
- Target Eye: None (Main)
![image](https://github.com/user-attachments/assets/ea481d7e-8549-461c-b5ab-df309222be39)

**HeadSpace Camera**
- Target Display: 2
- Target Eye: None (Main)
![image](https://github.com/user-attachments/assets/f5ce0ec3-4d77-4622-a035-d0da6fd12c8b)

**TrackingSpace Camera**
- Target Display: 3
- Target Eye: Both
![image](https://github.com/user-attachments/assets/12746c68-0438-4380-9244-9f84c3ebf3ed)

Note that you need an open gaming view in the inspector which renders to Display 3.
![Screenshot 2024-07-20 224011](https://github.com/user-attachments/assets/c8a05670-b7fa-4863-871b-d0ff92f3b6b5)
Hope this helps!

**Comment by paulstarke** [comment]
There is now a VR-demo .apk for this project that you can install on your headset without the need of link-cable.
