### ISSUE TITLE
Mac Unity4.5 open project show nothing, when i reimport Assets, show folders a while and then disappear immediately.

### ISSUE THREAD

**Issue by zzzkk2009** [sebastianstarke/AI4Animation#14]
infos like below:

![image](https://user-images.githubusercontent.com/3713481/44696009-4b56af80-aaa8-11e8-9552-410935cc356b.png)

![image](https://user-images.githubusercontent.com/3713481/44695989-3c6ffd00-aaa8-11e8-837f-c8375f9fd458.png)

can anyone know how to solve it?

**Comment by dyc3** [comment]
The project was created in Unity 2018.2.1f1, so it's probably not compatible that far backwards. The easiest solution would be to upgrade Unity to the latest version.
