### ISSUE TITLE
How can I get the input and output data？

### ISSUE THREAD

**Issue by ShadowZwx** [sebastianstarke/AI4Animation#15]
The data in URL(eg. http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/Output.txt) is so large that  the browser can't load it. So, how can I download the data by useful method？
Looking forward to your reply, thank you！

**Comment by elvis1423** [comment]
You can use these 2 commands:
curl http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/Input.txt >Input.txt
curl http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/Output.txt >Output.txt

**Comment by xcyan** [comment]
@sebastianstarke Would you please provide the training and testing split? Thanks!
