### ISSUE TITLE
MotionExporter output "output.txt" is incorrect.

### ISSUE THREAD

**Issue by satofd** [sebastianstarke/AI4Animation#19]
http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/Output.txt
There are 363 columns of this data.

https://github.com/sebastianstarke/AI4Animation/blob/master/AI4Animation/Assets/Scripts/DataProcessing/MotionExporter.cs#L244
Looking at where we write "output.txt" from line 244 to line 273, there seems to be only 360 columns of data.

The data for three columns is insufficient.

https://github.com/sebastianstarke/AI4Animation//blob/master/Media/SIGGRAPH_2018/Paper.pdf
Looking at Paper, "root translational x and z" and "root angular velocity" seem to be missing.

Is there a way to get the data for the three missing columns?

**Comment by Keneyr** [comment]
What I couldn't understand is that how you got the Input.txt & Output.txt files  since the raw motion data is .bvh or animation clips.  Have you used any software to convert the raw files to the .txt files? I really want to konw it. (I want to run the 2017Demo. but I don't know how to get the .txt files.)Anybody konws ? I really need your help.

**Comment by sebastianstarke** [comment]
There are two ways to compute the root offset. You can either predict it as the current (7th) trajectory point relative to the previous frame, or you compute the delta transformation between the current and next frame. Either way is fine actually, and both is sort of equivalent. The current version uses the first method, which makes the runtime easier as it only requires storing one (current) root. You can then compute the next trajectory by simply multiplying the root with each predicted next sample, and the 7th (first predicted) point becomes the new root. Hope this helps?

**Comment by sebastianstarke** [comment]
PS: I adjusted the motion exporter again accordingly. Thanks again for pointing this out!
