### ISSUE TITLE
Pretrained model weights

### ISSUE THREAD

**Issue by sneha-belkhale** [sebastianstarke/AI4Animation#20]
Hey, I was wondering if you had any saved weights after training with the data set you provided:

https://github.com/sebastianstarke/AI4Animation/blob/115b1b5ed65b703032c3861e10c353fa1cd11134/TensorFlow/SIGGRAPH_2018/data/Link.txt#L2

It would be nice to start experimenting with the project without having to wait xxx hours to train the model -- since I don't have any gpu's at my disposal :)

**Comment by sebastianstarke** [comment]
Hey there, yeah inside the Demo folders, there is a "Link.txt" file. You can get the weights for the published version here: http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/NN_Wolf_MANN.zip

**Comment by sneha-belkhale** [comment]
awesome, thanks!
