### ISSUE TITLE
Running on Android?

### ISSUE THREAD

**Issue by bitcloudTheFirst** [sebastianstarke/AI4Animation#22]
Hi, I know this probably isn't in the original scope, but I'm trying to build this project for Android, and I'm having no luck with Eigen. I've tried all manner of things. Did you have any ideas how we might be able to expand this to supporting android? Cheers

**Comment by sebastianstarke** [comment]
I just uploaded the source code for the Eigen plugin. I believe the plugin needs to be rebuilt for Android in this case, which process I am not very familiar with. Please let me know if you get it working! Thanks.

**Comment by ArkcS** [comment]
Sorry to bother you, but have you solved the problem?
