### ISSUE TITLE
Train failed

### ISSUE THREAD

**Issue by yh8899** [sebastianstarke/AI4Animation#23]
I use the "D1_001_KAN01_001.bvh" (only the one) to train the model. This is my Motion Editor setting 
![image](https://user-images.githubusercontent.com/5336422/65412434-cd3b1880-de21-11e9-9fbf-9fa324cd8848.png)
I want to test whether the Motion Exporter output data can be correct training. However, i failed. Can you help find the problem? This is my scene.
![image](https://user-images.githubusercontent.com/5336422/65412729-6a964c80-de22-11e9-96f3-a8f4d5ed8fff.png)
This is upside down.

**Comment by sebastianstarke** [comment]
Does the error happen during export or during train?

**Comment by yh8899** [comment]
> Does the error happen during export or during train? And is the screenshot of the character from the mocap or during runtime?

No error happen. The screenshot of character is from runtime. Is it my parameter setting error? This is my MontionExport settings.
![image](https://user-images.githubusercontent.com/5336422/65483081-899de880-decd-11e9-8416-1e31e30bd088.png)
 
![image](https://user-images.githubusercontent.com/5336422/65483100-9cb0b880-decd-11e9-9672-8cf99b172c9a.png)

**Comment by sebastianstarke** [comment]
I see, it looks like there is some mismatch of root information between data preprocessing and runtime. Does the data appear fine in the editor? Did you generate the data on a flat surface and not on the terrain one, and have the ground set to layer "Ground"? Do the poses and trajectory appear fine in the editor? Can you check in your exported data if the first joint (hip) is somewhere vertical above the root (above zero in local space)? If so, the data seems fine and the error should be somewhere in the runtime I would suspect.

**Comment by yh8899** [comment]
[Input.txt](https://github.com/sebastianstarke/AI4Animation/files/3645358/Input.txt)
[InputLabels.txt](https://github.com/sebastianstarke/AI4Animation/files/3645373/InputLabels.txt)
[Output.txt](https://github.com/sebastianstarke/AI4Animation/files/3645359/Output.txt)
[OutputLabels.txt](https://github.com/sebastianstarke/AI4Animation/files/3645384/OutputLabels.txt)

This is my Input and Output data. The InputLabels and OutputLabels are correct. I generate the data in your SIGRAPH_2018 demo scene, on the terrain. I have set layer mask to "Ground".

**Comment by yh8899** [comment]
Do you mean this value?
![image](https://user-images.githubusercontent.com/5336422/65484818-a0930980-ded2-11e9-9852-d030180ab61f.png)
And the hip joint relative to root is negative.

**Comment by sebastianstarke** [comment]
Okay, so things are going wrong because the terrain is used during data export. During the data generation, at every frame the root is projected on the ground below the hip. However, this terrain does not correspond to the captured motion. The pose is then transformed into the root space, but which is randomly changing depending on the height of the terrain. This causes the poses to become inconsistent in the exported data. Simply replace the terrain with a ground whose surface is at y=0 below the character, and it should work then.

**Comment by yh8899** [comment]
Thanks, that solve my problem. If export data on float ground, training it. Is it can run on a terrain?

**Comment by sebastianstarke** [comment]
This is done via IK post-processing on the output poses.

**Comment by yh8899** [comment]
I see, thank you very much.
