### ISSUE TITLE
FPNN input and output dimension

### ISSUE THREAD

**Issue by yh8899** [sebastianstarke/AI4Animation#24]
The input dimension different from the paper, which in the demo( SIGGRAPH_2017 Adam). This is the input in the paper:
![image](https://user-images.githubusercontent.com/5336422/65662021-cb619700-e065-11e9-887e-bdd8c323058a.png)
And this is the input dimension in the demo:
![image](https://user-images.githubusercontent.com/5336422/65662064-e46a4800-e065-11e9-9b5f-9413b75d3712.png)
X Dim is 468, but 330 in the paper. It is a little confuse.

**Comment by sebastianstarke** [comment]
The Adam version uses another feature setup than the original paper, which are mainly joint rotations included in the input.

**Comment by yh8899** [comment]
Thanks for your response. I found X dim is 342 in the original demo. Am i compute error or there are new feature included? Can you provide the Skeleton in the demo? I try to use the CMU mocap data to export the data, which have different skeleton structure. I do not know how to match the data with no skeleton.
