### ISSUE TITLE
unity to unreal

### ISSUE THREAD

**Issue by AFNANAMIN** [sebastianstarke/AI4Animation#25]
is it possible that i convert this project from unity to unreal

**Comment by sebastianstarke** [comment]
It surely is, but I can not estimate how difficult it is or how long it may take since I do not have much experience in Unreal.

**Comment by sebastianstarke** [comment]
It surely is as long as following the copyright information, but I can not estimate how difficult it is or how long it may take since I do not have much experience in Unreal.

**Comment by AFNANAMIN** [comment]
okay thanks

**Comment by hellozjj** [comment]
Have you done this?
