### ISSUE TITLE
Where is the input and output training data for PFNN? 

### ISSUE THREAD

**Issue by zijiaozeng** [sebastianstarke/AI4Animation#27]
Hi, 
   I can't find the training data for SIGGRAPH_2017,  the link file is empty.

Thank you!

**Comment by sebastianstarke** [comment]
For the original PFNN version, the training data and binary weights from Daniel Holden's website were used. For the Adam version, we used some other locomotion data that is part of the SIGGRAPH_Asia_2019 work (see locomotion folder there). However, I will try to update the SIGGRAPH_2017 folder soon as well. Thanks for pointing out!

**Comment by AndyVerne** [comment]
> For the original PFNN version, the training data and binary weights from Daniel Holden's website were used. For the Adam version, we used some other locomotion data that is part of the SIGGRAPH_Asia_2019 work (see locomotion folder there). However, I will try to update the SIGGRAPH_2017 folder soon as well. Thanks for pointing out!

Hi, I exported locomotion folder to "input.txt", "output.txt" and so on via Motion Exporter in \Assets\MotionCapture\Scene.unity as training data for PFNN(SIGGRAPH_2017). But the   weights and biases after training do not work well as the weights you provided in 'SIGGRAPH_2017\TensorFlow\trained_Adam' folder. Are there some details I missed or something I did in a wrong way?
Looking forward to your reply :)
My thanks.
