### ISSUE TITLE
Adam off from the Skeleton

### ISSUE THREAD

**Issue by xz6014** [sebastianstarke/AI4Animation#28]
Hey Sebastian,

When I was trying to run the demo, I noticed the mesh was off from the skeleton (as shown in the attached pic), could you please advise me what might have gone wrong there? 

Cheers

<img width="275" alt="off" src="https://user-images.githubusercontent.com/33828965/71900071-52da9e00-315d-11ea-97bc-462d6d6490c4.png">

**Comment by pauzii** [comment]
Hi there, probably this is caused by a different version of unity. Please make sure to use Unity version 2018.3.0f2 or similar.
