### ISSUE TITLE
How to train a fight animation?

### ISSUE THREAD

**Issue by hanbim520** [sebastianstarke/AI4Animation#3]
Hello, I compiled the Android version, found that can not be compiled successfully, lack of Library dependency, can you provide the dependent source code?
Since last year, I found your paper is waiting for your demo. Until recently, I saw that you posted it to GitHub. I am very interested in the application of AI in game, but I don't know much about neural network, so I can learn from your demo first.

**Comment by hanbim520** [comment]
I found that the relevant source code has been provided in the plugin directory, thank you.

**Comment by hanbim520** [comment]
I have build Windows version https://pan.baidu.com/s/1_UlJR8hWsFKQ2ANPidERfg,and make plugin project https://gitee.com/winemike/mfnn.git。Now there's only the Windows platform，then Android and  IOS

**Comment by hanbim520** [comment]
I don't know how to train a fight animation,like when other fight with you,or robot fight animation

**Comment by hanbim520** [comment]
![image](https://user-images.githubusercontent.com/7490792/37467515-6ad29e58-289b-11e8-8bf5-4013e5d696fd.png)
hello,I have recorder an animation,bug 
![image](https://user-images.githubusercontent.com/7490792/37469783-07ba4b4e-28a1-11e8-953f-898134e3d7b3.png)
those files do not exist.

**Comment by hanbim520** [comment]
Can anyone answer me?

**Comment by kuddai** [comment]
as far as I can see in this repo there is no learning code (all networks have only feedforward pass). It loads already trained weights from outside.

**Comment by sebastianstarke** [comment]
Hi guys, sorry for the later response. First of all, training a fighting animation is highly difficult and I think a little beyond the scope that is easily possible to do with current neural networks. We are researching on this. And yes, @kuddai is right that the Unity implementation that is so far contained only has the feedforward passes of the networks. Implementing a whole framework to do the learning in Unity would be an overkill for one person, so I just implemented that Eigen C++ wrapper which simply uses trained models. The training needs to be done outside. I will upload the Python code for the training with TensorFlow very soon.

**Comment by kuddai** [comment]
Have you considered using [this](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md) tensorflow port for Unity?

Btw, I liked your BFGS solver.

**Comment by sebastianstarke** [comment]
Thanks man! :) I have seen this repo, but not checked it yet. Did you, or can you recommend using it for deep learning in Unity? I might give it a try though in a couple of days ;)

**Comment by daniel-zimmermann** [comment]
This is fantastic work @sebastianstarke, and very impressive results, thank you for sharing! I would love to see your TensorFlow scripts and your implementation of AdamWR.

**Comment by johndpope** [comment]
fyi - training code https://github.com/ShikamaruZhang/MANN

**Comment by hanbim520** [comment]
Thank you for your answer. I've been very busy lately and haven't seen GitHub. I will continue to study this project later.

**Comment by sc1991327** [comment]
I lost all prefab information of this project when opened this project in unity in windows platform. @hanbim520  How to opened this project in unity in windows?
