### ISSUE TITLE
How do I try the project?

### ISSUE THREAD

**Issue by addeps3** [sebastianstarke/AI4Animation#31]
Hello, I saw a video about this project and would like to try it, but found no instruction on how to do it. 

I assume it is played in Unity game engine but I tried "Adding" the "Adam" folder in the Projects screen but it said that it was an invalid path. 

Can you please provide some instructions? 

With regards, John

**Comment by xiruiYan** [comment]
hi, have you solved this problem?

**Comment by sebastianstarke** [comment]
Hi, you'll need to import the Unity project by loading the folder that contains the Assets and ProjectSettings directories. In the 2017 version, you'll then need to press the "Store Parameters" button inside the neural network inspector, which loads the binary weights from the training folder, and hit the play button. The later versions should be ready to go directly. In the  Let me know if that works. Thanks!

**Comment by xiruiYan** [comment]
> Hi, you'll need to import the Unity project by loading the folder that contains the "Assets" and "ProjectSettings" directories. In the 2017 version, you'll then need to press the "Store Parameters" button inside the neural network inspector, which loads the binary weights from the training folder, and hit the play button. The later versions should be ready to go directly. Let me know if that works, thanks!

it works, thank you very much!

**Comment by qqcce** [comment]
> Hi, you'll need to import the Unity project by loading the folder that contains the "Assets" and "ProjectSettings" directories. In the 2017 version, you'll then need to press the "Store Parameters" button inside the neural network inspector, which loads the binary weights from the training folder, and hit the play button. The later versions should be ready to go directly. Let me know if that works, thanks!

Hi, could you explian in detail about how to find "Store Parameters" button or open neural network inspector?

**Comment by qqcce** [comment]
> > Hi, you'll need to import the Unity project by loading the folder that contains the "Assets" and "ProjectSettings" directories. In the 2017 version, you'll then need to press the "Store Parameters" button inside the neural network inspector, which loads the binary weights from the training folder, and hit the play button. The later versions should be ready to go directly. Let me know if that works, thanks!
> 
> it works, thank you very much!

Hi @xiruiYan, could you explian in detail about how to find "Store Parameters" button or open neural network inspector?
