### ISSUE TITLE
Ambiguities in reading the paper

### ISSUE THREAD

**Issue by acoMCMXCVI** [sebastianstarke/AI4Animation#32]
Hi Sebastian,
I'm new at r&d field, so i have a couple ambiguities in reading the paper. 
I don't understand why rotations  j^{r} belongs to R^{6}? 
And what is the root coordinate? 

![BBBB0B40-A620-497A-960D-EC747EAED76B](https://user-images.githubusercontent.com/54177130/83205122-031d6300-a14e-11ea-8702-28b6ef792e9c.jpeg)

Best,
Aleksandar

**Comment by sebastianstarke** [comment]
Hi Aleksandar!

We represent rotations in a 6D space that consists of two vectors, the forward and up direction of a Cartesian coordinate frame. Using those two vectors gives a continuous interpolation space for training neural networks, which is not the case when using some form of quaternion or Euler-angle representation.

The root coordinate is the world-to-character transformation matrix, which means we learn the poses in the local character space.

Hope that helps!

**Comment by acoMCMXCVI** [comment]
Thank you very much, that was helpful!
