### ISSUE TITLE
Eigen bundle is broken for macOS

### ISSUE THREAD

**Issue by xiaxx244** [sebastianstarke/AI4Animation#33]
Hi，when I try your project on macOS，it says that the eigen bundle is broken，can you fix that issue？thanks！

**Comment by sebastianstarke** [comment]
Which project are you trying, the PFNN, MANN or NSM? I do not have a Mac with me right now, but will look into that and recompile the library asap. Otherwise, if you are familiar with compiling C++ code into native libraries, I can also forward you the source code of that bundle. Let me know :)

**Comment by kidach1** [comment]
@sebastianstarke 
Hi, Could you share the C++ code of eigen for NSM? Thanks.

**Comment by sebastianstarke** [comment]
Sorry for the delayed response. I just uploaded the C++ source code for the Eigen plugin. Thanks!

**Comment by MohameHassan** [comment]
Hi @sebastianstarke 
I am facing the same issue, could you please provide some info about how to solve/compile this?

Thanks!

**Comment by sebastianstarke** [comment]
I have not much experience using macOS, so unfortunately I can not really assist here. However, I know from a collaborator that he was able to compile the Eigen C++ into a .bundle file as a native plugin for Unity. There are also some tutorials for that available if I remember right. Note that the function names in the .cpp might have changed over projects, so maybe a few adjustments may be necessary when recompiling the plugin for previous versions, so Unity can find all entry points (don't worry, it will tell you which ones). Feel free to drop me a mail if you have questions about that.

**Comment by mrmotallebi** [comment]
Was anyone able to resolve this?
