### ISSUE TITLE
Network weights for Adam in PFNN

### ISSUE THREAD

**Issue by Fiona730** [sebastianstarke/AI4Animation#34]
Hi, thanks for your awesome work!
I noticed that there is neither pretrained weights nor training data for the Adam model in PFNN. Just want to confirm whether these data are unreleased, in case I missed them somewhere.

**Comment by sebastianstarke** [comment]
Hi there!
Oh right, I should update that Adam PFNN example probably. Will do that later today!
Apart from that, there is a file [Link.txt](https://github.com/sebastianstarke/AI4Animation/blob/master/AI4Animation/SIGGRAPH_2017/Unity/Assets/Demo/Adam/Link.txt), which forwards to the [location](http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2017/NN_Adam_PFNN.zip) where the pretrained weights are saved. I think this should work for now, but I will look into that later today how to ease that process. Wanted to do that anyways, so thanks for pointing this out! :)

**Comment by Fiona730** [comment]
Thanks so much for your quick reply and the weights file! I am working on intergrating PFNN into a new model and the weights for Adam provides much convenience :)

**Comment by Fiona730** [comment]
Hi, I want to adjust the Adam character to perform terrain-adaptive locomotion. As Adam has different bone structure with the original model, did you use new mocap data for training?
I plan to follow the steps in the PFNN paper, first perform terrain fitting on the new data, then alter input and output dimensions to include height information, and finally retrain the network. Would that work?
Thanks again for your help :)

**Comment by Fiona730** [comment]
Hi, I want to adjust the Adam character to perform terrain-adaptive locomotion. As Adam has different bone structure with the original model, did you use new mocap data for training?
I plan to follow the steps in the PFNN paper, first perform terrain fitting on the new data, then alter input and output dimensions to include height information, and finally retrain the network. Would that work?
Thanks again for your help :)
