### ISSUE TITLE
siggraph 2020 code release date?

### ISSUE THREAD

**Issue by whatsdis** [sebastianstarke/AI4Animation#37]
when can we expect to see a unity project source code to test this out?

**Comment by HiddenStar0412** [comment]
I am also very interested in this!
Good job!
I am trying to do this project.
Can I train the character of basket ball player myself?

**Comment by han-x** [comment]
Aha This  is a very fantastic work, and I am looking forward to it!

**Comment by fuying-wang** [comment]
This is an awesomw work! I am looking forward to seeing the code.

**Comment by luoruiming** [comment]
can't wait to see the code!

**Comment by pkpp1233** [comment]
+1. Great work!

**Comment by jintemp** [comment]
+1， expect

**Comment by hellozjj** [comment]
+1， expect

**Comment by Qix-** [comment]
Please stop spamming "+1". Use Github's reaction feature, please. Everyone gets a notification and/or an email every time you do so.

**Comment by dragonballa** [comment]
> Please stop spamming "+1". Use Github's reaction feature, please. Everyone gets a notification and/or an email every time you do so.
> 
> Also, stop "expecting" things. The maintainer is under no obligation to you; you are not compensating them for their work.

you can unsub from the thread. I think we all know how open source works.

**Comment by Qix-** [comment]
You're gravedigging a 2.5 year old ticket to respond to a 1.5 year old comment just to post a snarky comment on Christmas day. Bravo.

**Comment by dragonballa** [comment]
> You're gravedigging a 2.5 year old ticket to respond to a 1.5 year old comment just to post a snarky comment on Christmas day. Bravo.

the pot calling the kettle black LMAO

**Comment by pauzii** [comment]
Code can be found here https://github.com/sebastianstarke/AI4Animation/tree/master/AI4Animation/SIGGRAPH_2020
