### ISSUE TITLE
Unreal version

### ISSUE THREAD

**Issue by juaxix** [sebastianstarke/AI4Animation#39]
Are you planning to support Unreal Engine?

**Comment by sebastianstarke** [comment]
Unfortunately no. I am not very experienced developing in Unreal Engine.

**Comment by juaxix** [comment]
Don't close the ticket please, I would like to port it :)

**Comment by Qix-** [comment]
@juaxix You should fork it :) Otherwise, he'd have to maintain it, too.

**Comment by sebastianstarke** [comment]
Yeah, a fork will be great! :) Happy to help with questions regarding the code structure and workflows.

**Comment by juaxix** [comment]
Ok, I am going to fork it , I think I can use the plugin C++ source directly in UE

**Comment by juaxix** [comment]
I forgot I cloned the project years ago, I have updated it added the UE project with the port for the Eigen plugin (Unreal Engine comes with another version of Eigen though), link here:
https://github.com/juaxix/AI4Animation/tree/UnrealEngine_4_25
what should be the next step?

**Comment by lukaszml** [comment]
I think it would be a sensible next step to convert SIGGRAPH 2018 and 2019 Asia, to UE4. Next, keeping up to date with the master repo.

**Comment by juaxix** [comment]
Sorry, I only ported the Eigen plugin for the moment, but I don´t know where to start now regarding the unity project , architecture, files and so on. What I did was just to create a project with a third person template, the Eigen plugin and nothing more.

**Comment by juaxix** [comment]
Can you take a look to the generation of the matrices from the files in MANN and PFNN models? 
https://github.com/juaxix/AI4Animation/commit/bf9386a935bbfe8f72362f04eff30262ce7d314d
thanks

**Comment by juaxix** [comment]
Hello, can you check the current state? 
https://youtu.be/JBD2V5VnJ0k
thanks.
Source:
https://github.com/juaxix/AI4Animation/tree/UnrealEngine/AI4Animation/SIGGRAPH_2018/Unreal

**Comment by SlimeVRX** [comment]
@juaxix Hello,

I'm starting to learn about Motion Matching

Goal: Combines the mocap system with 6 inertial sensors and Motion Matching to move the character on a variety of terrain

Do you have any advice for me? I'm also working with Unreal

Thank you very much!

**Comment by juaxix** [comment]
I would love to but I think we need to translate that question to Sébastien...

**Comment by SlimeVRX** [comment]
Salut @juaxix

Je commence à en apprendre davantage sur Motion Matching

Objectif : combinez un système de mocap et de correspondance de mouvement pour que le personnage se déplace sur plusieurs terrains et transforme les objectifs d'action tels que le déplacement de la position de la chaise afin que le personnage puisse se mettre en position et s'asseoir.

Avez-vous des conseils pour moi? Je travaille aussi avec Unreal

Merci beaucoup!

**Comment by 0mil** [comment]
Hello @juaxix,
Are you still there?

Can I ask a question related to the process of converting projects from Unity to Unreal? (I am currently trying on this)
I am encountering issues with converting Unity's transform matrix (Matrix 4x4) to Unreal's transform matrix (FMatrix).

For instance, when creating transform matrices for the same position (10, 20, 30), rotation (30, 40, 50), and scale (1, 2, 3) in both Unity and Unreal, I end up with different 4x4 matrices. The issue does not seem to be resolved by simple way like Unity's coordinate system converts to Unreal's (X, Y, Z to X, Z, Y) nor by transposing the column-major order to row-major order.

The mismatch seems to lie within the 3x3 matrix part of the transform matrix 4x4(without translation row), which involves rotation and scale. If you know the reason for this mismatch or have any advice, I would greatly appreciate it.

**Comment by juaxix** [comment]
I am not sure if I understand the problem, I think I did this (2 years ago now wow) just by converting the functions and using the ones in the UE maths. I don't know what's the reason of the mismatch ,maybe it would help with an example and see if anyone here @0mil , @sebastianstarke , @SlimeVRX could reply.
