### ISSUE TITLE
data url of SIGGRAPH_2018 can not available in path AI4Animation\SIGGRAPH_2018\TensorFlow\data\Link.txt

### ISSUE THREAD

**Issue by TomatoBoy90** [sebastianstarke/AI4Animation#40]
Download the training data into this folder from:
http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/Input.txt
http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/Output.txt

howerver, find result as follow：
`
502 Couldn't parse server headers
The following error occurred while trying to access http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/Input.txt:

502 Couldn't parse server headers

Generated Mon, 21 Sep 2020 08:21:34 GMT by Polipo on SKY-20191018RRI:8123.
`

**Comment by pauzii** [comment]
Hi there, this happened probably because the links were out of date. Please download the training data from
http://www.starke-consult.de/AI4Animation/SIGGRAPH_2018/Input.txt
http://www.starke-consult.de/AI4Animation/SIGGRAPH_2018/Output.txt
