### ISSUE TITLE
Data for SIGGRAPH_Asia_2019

### ISSUE THREAD

**Issue by lockhaicttv** [sebastianstarke/AI4Animation#41]
Dear all,

I am trying to implement the code in Data for SIGGRAPH_Asia_2019.
Unfortunately, I don't know how to get the data for training.
Could you help me?

Thank you

**Comment by sebastianstarke** [comment]
You'll need to open the motion capture scene and then open the Motion Exporter editor window (AI4Animation -> Motion Exporter). Make sure that the action and style labels that you wish to export are selected in the inspector, this is important to get the correct feature setup in the generated data files. The exporter will generate the input and output files from which the network can be trained.
