### ISSUE TITLE
In SIGGRAPH_2017,  I tried to import and run the unity project in unity, after I built and ran , the character can't be controlled when I pressed W,A,S,D keys on keyboard.

### ISSUE THREAD

**Issue by AndyVerne** [sebastianstarke/AI4Animation#42]
Hello, I even tried to directly built and ran project of unity in SIGGRAPH_2017 without editing. But in the program have built, the character doesn't respond to my input. And one more question, how could I use the weights I trained in PFNN to unity project? 
Thank you so much. By the way, I really appreciate your work in AI4Animation. Hope you have a nice day : )

**Comment by AndyVerne** [comment]
Sorry to bother you in this way. I am new to AI and unity field. I already handled it by myself. :)

**Comment by milkcat0904** [comment]
hello i got this problem too, could u plz tell me how to fix it

**Comment by AndyVerne** [comment]
> hello i got this problem too, could u plz tell me how to fix it

You need to find "store parameters" button in unity and click it before you click play button.
Hope that it can help you.

**Comment by qqcce** [comment]
> > hello i got this problem too, could u plz tell me how to fix it
> 
> You need to find "store parameters" button in unity and click it before you click play button.
> Hope that it can help you.

Can you explain in detail about how to find the "Store parameters" button?

**Comment by miaoYuanyuan** [comment]
> Sorry to bother you in this way. I am new to AI and unity field. I already handled it by myself. :)

Can you give a sreenshot about the "Store parameters" button? I can't find this button

**Comment by jinfagang** [comment]
How to find the pfnn panel? I can not found any pfnn panel there.
