### ISSUE TITLE
No Motion Editor found in scene in PFNN unity project

### ISSUE THREAD

**Issue by AndyVerne** [sebastianstarke/AI4Animation#44]
Hi! I am new to unity and this project. And I got one problem for your help : ( After I imported BVH file using Data Processing/BVH importer in the demo_adam (and demo_original) , and I wanted to export the BVH file to input.txt and output.txt as the training data. The Motion Exporter just shows that "no motion editor found in scene". I have no clue to solve this out.  Is there missing scene.unity file in this project?

**Comment by MohameHassan** [comment]
You need to open the MoCap scene which has the Motion Editor as written in the instruction 
https://github.com/sebastianstarke/AI4Animation/blob/master/AI4Animation/SIGGRAPH_Asia_2019/Unity/Assets/ReadMe.txt

**Comment by AndyVerne** [comment]
> You need to open the MoCap scene which has the Motion Editor as written in the instruction
> https://github.com/sebastianstarke/AI4Animation/blob/master/AI4Animation/SIGGRAPH_Asia_2019/Unity/Assets/ReadMe.txt

Thanks for your reply:)
Does it actually mean there is no Motion Editor in unity of PFNN(SIGGRAPH_2017)? So if I need to use the Motion Editor, I have to use the MoCap scene built in SIGGRAPH_Asia_2019 project?

**Comment by sebastianstarke** [comment]
Hi Andy, I think the PFNN 2017 project has a MotionEditor.cs script, it just does not have any pre-made scene already setup for exporting. You would need to create a new scene, create an empty game object and add the MotionEditor script to it. The MotionExporter is then using the MotionEditor to load and iterate over the data and collect the required information from the MotionData asset files. Hope that helps? Let me know, thanks!

**Comment by AndyVerne** [comment]
> Hi Andy, I think the PFNN 2017 project has a MotionEditor.cs script, it just does not have any pre-made scene already setup for exporting. You would need to create a new scene, create an empty game object and add the MotionEditor script to it. The MotionExporter is then using the MotionEditor to load and iterate over the data and collect the required information from the MotionData asset files. Hope that helps? Let me know, thanks!

Yeah! Due to lack of knowledge of Unity. It took my a few hours till I made it by following your instructions. It did work out. Your instructions help me a lot. Thank you so much! 👍 
By the way, I also got one personal question. I used the BVH motion data of the original PFNN(theano version) project to export to input.txt, output.txt as training data in this PFNN(tensorflow version) project, but the training result did not work well. :(

**Comment by hellozjj** [comment]
> > Hi Andy, I think the PFNN 2017 project has a MotionEditor.cs script, it just does not have any pre-made scene already setup for exporting. You would need to create a new scene, create an empty game object and add the MotionEditor script to it. The MotionExporter is then using the MotionEditor to load and iterate over the data and collect the required information from the MotionData asset files. Hope that helps? Let me know, thanks!
> 
> Yeah! Due to lack of knowledge of Unity. It took my a few hours till I made it by following your instructions. It did work out. Your instructions help me a lot. Thank you so much! 👍
> By the way, I also got one personal question. I used the BVH motion data of the original PFNN(theano version) project to export to input.txt, output.txt as training data in this PFNN(tensorflow version) project, but the training result did not work well. :(



Can you teach me How to export original PFNN BVH data to generate input.txt?

**Comment by hellozjj** [comment]
> Hi Andy, I think the PFNN 2017 project has a MotionEditor.cs script, it just does not have any pre-made scene already setup for exporting. You would need to create a new scene, create an empty game object and add the MotionEditor script to it. The MotionExporter is then using the MotionEditor to load and iterate over the data and collect the required information from the MotionData asset files. Hope that helps? Let me know, thanks!

I follow your instructions. Import BVH, creat a scene and an empty object, then I add the MotionEdit.cs to the object. But when generate input.txt after click the 'import' of the MotionEdit planner, the actor becomes unnormal. Which actor I should use when generate input.txt for the original PFNN BVH data?
