### ISSUE TITLE
How to export the animation data?

### ISSUE THREAD

**Issue by KartikShrivastava** [sebastianstarke/AI4Animation#45]
Hi,
I'm trying to use ```MotionExporter``` and ```MotionEditor``` to export the animation files but it's looking for some files to get current frame and initialize ```Editor.Files``` which I don't know how to generate? Can you please tell me how can I do that.

**Comment by sebastianstarke** [comment]
You'll need to first import motion asset files from .bvh or .fbx format into Unity, which can then be loaded into the motion editor.

**Comment by sebastianstarke** [comment]
You'll first need to import motion asset files from .bvh or .fbx format into Unity (see the provided importers), which can then be loaded into the motion editor.

**Comment by KartikShrivastava** [comment]
Hi,
I've imported the asset files from the ```Mocap Data``` provided in the repository using ```BVH Importer```, then specified the destination folder path in ```Motion Editor``` ```Folder```, but on pressing the ```Export Data``` button in ```MotionExporter``` I'm getting an error in which ```Means``` are not initialized. Also, ```Editor.Files[i].Data.Export``` is false for all the files.

**Comment by zll961020** [comment]
Hi,
I want to use new motion data to export new training data for the model in SIGGRAPH_Asia_2019, now I use the FBX Importer to import animation, but when I put the "play" button in the Motion Editor panel, the character does not move. It seems that the skeleton of new data is different from that of the Character(Actor) in the project. So, how can I use my new motion data with new skeleton? Thank you！

**Comment by pauzii** [comment]
@KartikShrivastava please make sure to correctly load the imported assets into the Motion Editor and to set the export boolean to true by clicking the corresponding button in the inspector. Could you provide a specific error output where "Means" are not initialized?

**Comment by pauzii** [comment]
@zll961020 Please use the corresponding UI elements in the inspector to play your imported animation data. The Motion Editor runs in unity edit mode and does not require play mode. Once you have loaded the assets into the Motion Editor, make sure that the right bones of the skeleton is selected in the inspector of Actor.cs (component of your Character).
