### ISSUE TITLE
Y Dimension in the MANN demo does not match with description in paper

### ISSUE THREAD

**Issue by SoerenFrohne** [sebastianstarke/AI4Animation#50]
I have a question regarding Mode-Adaptive Neural Networks. In the paper, the output vector consists of the trajectory position, direction and velocity values (2t values each). In addition, there is information on joint positions and velocities (3j values each) and rotations (6j values). Finally, three values describe the state of the root transform. 
If I have calculated correctly, this results in a total of 12j+6t+3 values. So for the 27 joints and 12 time samples mentioned in the example, one would expect a dimension of 399 output values. However, the "Y Dim" parameter in the demo is only set to 363. Is there a reason for this?

In addition, I would like to know the function of the "Y Dim Blend" parameter (19).

Best regards and keep up the good work!

**Comment by bmahlbrand** [comment]
Did you figure this out?
