### ISSUE TITLE
SIGGRAPH 2020，Code (coming soon)

### ISSUE THREAD

**Issue by jintemp** [sebastianstarke/AI4Animation#51]
SIGGRAPH 2020，Code (coming soon)，Hi，May I ask when it will appear

**Comment by hellozjj** [comment]
I want to know too.

**Comment by yhyu13** [comment]
Same question

**Comment by qiufeng1994** [comment]
Same question

**Comment by pauzii** [comment]
Code is to be found here https://github.com/sebastianstarke/AI4Animation/tree/master/AI4Animation/SIGGRAPH_2020
