### ISSUE TITLE
git LFS over data quota

### ISSUE THREAD

**Issue by nicolas42** [sebastianstarke/AI4Animation#54]
Was trying to download the motion capture data but it seems like git LFS is over its limit.  Is there any other way of getting or even just looking at some of this data?

Here's the error

Downloading Media/SIGGRAPH_2018/Mocap.zip (37 MB)
Error downloading object: Media/SIGGRAPH_2018/Mocap.zip (59585e5): Smudge error: Error downloading Media/SIGGRAPH_2018/Mocap.zip (59585e502d71c3d565952b0b7015312e2e3969997bd4113dde976e39472379b5): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /home/sch600/thesis/sebastianstarke/AI4Animation/.git/lfs/logs/20210506T170624.162556045.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Media/SIGGRAPH_2018/Mocap.zip: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by sebastianstarke** [comment]
Thanks for pointing out, should be working again now!
