### ISSUE TITLE
How to understand the "Root" in the paper of SIGGRAPH_Asia_2019

### ISSUE THREAD

**Issue by zll961020** [sebastianstarke/AI4Animation#57]
Hi,
@sebastianstarke The features about current Fame input contains the joint position,rotations and velocities relative to the root coordinate in the previous frame, however, the “root” it doesn't seem to refer to the Hips joint. Then, what it means ? How can I can its info? Thank you very much!

**Comment by sebastianstarke** [comment]
The root refers to a projection of the hip on the ground, with the Z-axis facing forward and Y-axis pointing up in world space.
