### ISSUE TITLE
corrupt archive?

### ISSUE THREAD

**Issue by whynames** [sebastianstarke/AI4Animation#58]
It says archive is corrupt in winrar

**Comment by sebastianstarke** [comment]
Please try opening with 7zip, or let me know if the issue persists. Thanks!

**Comment by cjlong1213** [comment]
![image](https://user-images.githubusercontent.com/15936033/123198103-221c2f00-d4df-11eb-97d9-b6740665e307.png)
Please help to check, some xml file is invalid.

**Comment by sebastianstarke** [comment]
I just tested downloading the repository, unzipping and importing and everything is working for me. Can you provide more information how to reproduce the issue?

**Comment by sebastianstarke** [comment]
I just tested downloading the repository, unzipping and importing and everything seems working fine for me. Can you provide more information how to reproduce the issue?
