### ISSUE TITLE
On what kind of hardware was everything trained?

### ISSUE THREAD

**Issue by wwwonka** [sebastianstarke/AI4Animation#59]
Hi Sebastian,
First of all thank you for sharing your truly amazing work. I believe I am not the only to be stunned by the quality of your research.

On the path to reproduce the results, I see in the [README](https://github.com/sebastianstarke/AI4Animation/blob/master/AI4Animation/SIGGRAPH_Asia_2019/Unity/Assets/ReadMe.txt#L17) of the SIGGRAPH_ASIA_2019, you say « wait for 1-2 days», can you be a litle more specific about the hardware you used to train your model?

cheers

**Comment by sebastianstarke** [comment]
Hi @wwwonka, the training hardware should be mentioned in the paper, which I believe was a GTX 1080 model. Should be faster nowadays! ;)
