### ISSUE TITLE
Copyright question

### ISSUE THREAD

**Issue by andybak** [sebastianstarke/AI4Animation#6]
I read the copyright statement in the readme with great interest and I don't have a fundamental problem with academic institutions maintaining ownership of IP generated under their auspices.

However I would like to ask whether this licencing is the default for all and any code generated in your University or whether there is a specific decision to apply it to some projects that might otherwise have been released under an open source licence.

I would actually prefer it if it turned out to be the second case. i.e. it wasn't a blanket default policy but was applied selectively when there was a genuine chance of commercial benefit.

**Comment by sebastianstarke** [comment]
Added a proper license specification to the repository. Hope this resolves the question! Thanks.
