### ISSUE TITLE
How do I add my custom animations for training?

### ISSUE THREAD

**Issue by Elie-1996** [sebastianstarke/AI4Animation#63]
Is there any guide on importing? I know it is under AI4Animation->FBX Importer. (for example) but how should the files look like? What do I put in those boxes? When I import, where will all the scene and animation files be?

Thanks

**Comment by sebastianstarke** [comment]
Hi there, the FBX importer works a bit different than the BVH importer.

For the BVH importer, one would just need to specify the path where the source data is saved (i.e. the raw .bvh files), and specify the local asset path inside Unity where the imported files should be saved.

For the FBX importer, it is necessary to first drag&drop the source FBX files into Unity, and then specify the path to this local folder in the FBX importer and where the re-processed files shall be saved. The FBX files can be deleted again afterwards.

Note that all imported assets in the AI4Animation framework will be in form of MotionAsset types deriving from ScriptableObject, which enables them to be loaded by the MotionEditor for further processing or labeling.

Let me know if that helps or if any other questions! (PS: This is for the source code of the 2020 project)

**Comment by Elie-1996** [comment]
Thank you for the quick response, I will attempt this soon and update!

**Comment by Elie-1996** [comment]
Hi Again, I animated a dummy object in Maya and exported as FBX. 
I'm trying to import this into Unity but nothing is happening.

![image](https://user-images.githubusercontent.com/44254485/129603977-6fca82e1-1cec-4b7c-9ee6-010e5d74752f.png)

Did I miss a step?
