### ISSUE TITLE
Could you please provide the fbx file of wolf used in MANN Project?

### ISSUE THREAD

**Issue by NoName1022** [sebastianstarke/AI4Animation#64]
Hello, I am very interested in the great ideas of using end-to-end neural networks to predict motion in the paper "Mode-Adaptive Neural Networks for Quadruped Motion Control“. 
I am trying to repeat this work in a different engine, but I found the Wolf prefab actually used in Unity project is different from the fbx file located at Assets/Palette/Wolf/Model/ path. The name of bones displayed in Actor component and transforms of bones can't correspond to Assets/Palette/Wolf/Model/Wolf.fbx. I tried use fbx exporter plugin to export prefab to fbx but failed (bones got messed up in exported file). Could you provide a fbx or obj file corresponding to the prefab placed in the demo scene?

**Comment by whitealex95** [comment]
Any follow up on this issue?

**Comment by NoName1022** [comment]
I guess the model in the scene has been modified by C# code. now I don't need to repeat MANN on another engine so I will close this issue.
