### ISSUE TITLE
SIGGRAPH Asia 2019 : Dimension MisMatch

### ISSUE THREAD

**Issue by aymenmir1** [sebastianstarke/AI4Animation#68]
In the main file, the starting goal index is `419` but in the file InputLabel.txt that I obtain by running your Unity script, startGoal is `445`.

In the Input.txt and InputLabels.txt files, the total dimension of the inputs is 5567, but if I sum up the dimensions listed in the main file, the input dimension should be 5307, (start_gating = `4657` + dim_gating = `650`). 

I assume that the dimensions listed in the main file are incorrect or is it that there were some problems in running the Unity scripts on my end. I used Unity 2020.

**Comment by sebastianstarke** [comment]
I just checked and all seems fine for me, so wondering what causes this issue. I opened the Unity project from scratch (only Assets and ProjectSettings folders), went to the mocap scene and exported data, and total input dimension was 5307 as expected (also similiar with the feature dimensions in the runtime code). I opened the project with Unity 2018.3.0f2. Would you be able to try using that version?
