### ISSUE TITLE
[SIG-2017] Question regarding FootIK file

### ISSUE THREAD

**Issue by yunfei-teng** [sebastianstarke/AI4Animation#69]
Hi Sebastian,

Thanks for sharing the codes and it is really nice! I am currently running the codes of SIG-2017 within Unity. I tried to quantitively measure the sliding of the human model when walking and running. I found there is a CS file named FookIK seeming suitable to that task and I have two questions to ask:

1. I found there is a visualizing function *OnDrawGizmos* but I could not see anything even if I select 'visualize' in unity. Do I have to install OpenGL or something else?
2. Is there anyway I could find the mapping between the bone index and actor's component?

Thank you!

**Comment by sebastianstarke** [comment]
Hi, can you check if the "Gizmos" button in Unity is active? It controls whether OnDrawGizmos is called or not. Regarding the mapping, it should be computed somewhere inside the LoadFrame function in the MotionEditor.
