### ISSUE TITLE
Will the raw data and preprocessing code be released?

### ISSUE THREAD

**Issue by sleeepyy** [sebastianstarke/AI4Animation#7]
I am now trying to go through the whole process, from mocap data to trained model and use it to generate  motion. The pfnn codes and data are for humanoid. I wonder whether the wolf raw data and processing codes will be released.

**Comment by sebastianstarke** [comment]
The data is already released (see ReadMe file for path). You'll then need to use the BVHImporter and MotionEditor / MotionExporter addons inside Unity to process the motion and generate the training data. I am currently updating these scripts to be more "modular", so I would suggest you wait a few days until you do the whole process on your own. Anyways, you can of course try it out already to get an idea of how it works. Feel free to write me a mail if you have any questions.

**Comment by sleeepyy** [comment]
Thank you!
