### ISSUE TITLE
Predefined trajectories generation

### ISSUE THREAD

**Issue by HaozhouPang** [sebastianstarke/AI4Animation#71]
Hello Sebastian,

As for the evaluation of responsiveness, if I understand the paper correctly, I believe you blend the predicted future trajectory with a predefined trajectory to make the character follow a specific path. I am wondering how the predefined trajectory was generated, did it come from a Mocap clip and got processed by the MotionExporter? or was it generated by a script? If the latter, could you share how to generate predefined trajectories with smooth transition.

Much appreciated,
Haozhou.

**Comment by pauzii** [comment]
Hi there, could you specify which paper you are referring to?

For the experiments in the papers, in some cases the ground truth trajectory is used which is extracted from the asset files that have been imported (Motion Importer scripts). If you are referring to the MANN paper (2018) one experiments visualizes a pre-defined trajectory. In this case, Catmull-Rom splines are used to generated a smooth control trajectory. You can use this authoring tool to create your own predefined trajectories on the ground and generate smooth transitions between actions: https://github.com/pauzii/AnimationAuthoring

Hope this helps!
