### ISSUE TITLE
How to turn while walking?

### ISSUE THREAD

**Issue by zll961020** [sebastianstarke/AI4Animation#73]
Hello Sebastian Starke, I wonder how to implement turn while walking? Is the model's own capabilities while given the key command such as W and E at the same time or there exists some process of camera to achieve this? Hope for you reply, many thanks.

**Comment by Hlxwk** [comment]
Feed the model with the turning trajectory.

**Comment by zll961020** [comment]
> Feed the model with the turning trajectory.
Thanks for your replay.
