### ISSUE TITLE
how to process different sequences in export period

### ISSUE THREAD

**Issue by xjturobocon** [sebastianstarke/AI4Animation#79]
`// foreach(Sequence seq in Editor.GetData().Sequences) {`
`Sequence seq = Editor.GetData().GetUnrolledSequence(); {`

Hey, In MotionExport.cs file, you comment the top line, and use the bottom line code. I mentioned you split a whole sequence motion into several sequences, the top one code can process them seperately, but the bottom one just ignore the split and process the whole one.
Why did you choose to do that? Is threr any problem if I use the top one line?

**Comment by pauzii** [comment]
Hello, thank you for mentioning this. The comment should be undone to fulfill intended behavior.

To process several different sequences in a single clip please use `foreach(Sequence seq in Editor.GetData().Sequences) {`. This will process all the frames that are included in those defined sequences and ignore any other frames. 

`Sequence seq = Editor.GetData().GetUnrolledSequence();` was used for a single experiment and transforms your sequences into a single sequence based on the first and last frame. This can include frames that are not within your defined sequences and hence you don't want to process.
