### ISSUE TITLE
How do I add the status of a quadruped and use it in unity?

### ISSUE THREAD

**Issue by YLe1201** [sebastianstarke/AI4Animation#80]
In BasketballDemo scene 2020，I'm trying to export new styles of the quadruped，such as sit. I trained the output data, but the results can't be applied in the QuadrupedDemo scene. The quadruped's sitting state is wrong. What is the reason，Is there any problem？

**Comment by pauzii** [comment]
Did you doublecheck the style vector in the controller, which may be of different dimensionality for your own featured dataset?
