### ISSUE TITLE
resource 403

### ISSUE THREAD

**Issue by ploirliu** [sebastianstarke/AI4Animation#81]
as for resource:   http://www.starke-consult.de/AI4Animation/SIGGRAPH_2018/MotionCapture.zip

it shows:
![image](https://user-images.githubusercontent.com/10735783/173038234-d098206c-dfbb-4258-98fa-9244722eaade.png)

**Comment by lvZic** [comment]
still unavailable

**Comment by pauzii** [comment]
Link is working for me. Double check your URL
