### ISSUE TITLE
SIG-2020：Are the style signals also be labeled automatically? If so, how to calculate?

### ISSUE THREAD

**Issue by zll961020** [sebastianstarke/AI4Animation#83]

**Comment by pauzii** [comment]
The styles can be automatically labeled as a pre-processing step using different heuristic functions. You can find those 
in the MotionProcessor: https://github.com/sebastianstarke/AI4Animation/blob/master/AI4Animation/SIGGRAPH_2020/Unity/Assets/Scripts/DataProcessing/Processor/MotionProcessor.cs
