### ISSUE TITLE
SIGGRAPH 2022，Code (coming soon)

### ISSUE THREAD

**Issue by zll961020** [sebastianstarke/AI4Animation#85]
Hello, Sebastian. May I ask when the code will be uploaded? @sebastianstarke

**Comment by dragonballa** [comment]
we've been waiting for years. Electronic Arts probably got to him first.

https://github.com/sebastianstarke/AI4Animation/issues/37

**Comment by carlosedubarreto** [comment]
I think this is what you are searching for
https://github.com/sebastianstarke/AI4Animation/tree/master/AI4Animation/SIGGRAPH_2022/PyTorch
