### ISSUE TITLE
Is it possible to run at 30hz? (SIGGRAPH_2017)

### ISSUE THREAD

**Issue by benjaminnoer2112** [sebastianstarke/AI4Animation#88]
This code is included with a comment saying it is for 60hz (BioAnimation_Adam.cs):

```
//Trajectory for 60 Hz framerate
private const int Framerate = 60;
private const int Points = 111;
private const int PointSamples = 12;
private const int PastPoints = 60;
private const int FuturePoints = 50;
private const int RootPointIndex = 60;
private const int PointDensity = 10;
```

Is it possible to change these values to have it run at 30hz? If so, aside from changing the 'Framerate' variable to 30, what other values need to be changed?

**Comment by pauzii** [comment]
Hi there, changing the framerate parameter in the controller should be sufficient. However, you also want to retrain the model on 30hz instead of 60Hz. by shifting every 2nd frame in the data. The original mocap data was captured at 60Hz.
