### ISSUE TITLE
How to translate these Animation to a new Model

### ISSUE THREAD

**Issue by Pavankunchala** [sebastianstarke/AI4Animation#92]
Lets say I have a fbx model, I am curious on how to translate the basket ball animation to the fbx model 

I would love to know if there is any documentation on how to use this repo

**Comment by NicTanghe** [comment]
You could use houdini.
https://www.youtube.com/watch?v=B4RT4OLu5E8

**Comment by pauzii** [comment]
If your fbx model has a different skeleton you will have to train a new GNN network for it.
If not, you will need to apply the actor.cs script to your game character and reference it in the controller.
