### ISSUE TITLE
error while training on pytorch SIGGRAPH_2022

### ISSUE THREAD

**Issue by kotaxyz** [sebastianstarke/AI4Animation#94]
i get this error when i try to run training 

` (DeepPhaseSubmission) C:\Users\Genesis\unity ai\SIGGRAPH_2022\PyTorch\PAE>python Train.py
Loading Dataset/DataShape.txt
Loading Dataset/Sequences.txt
Generating Data Sequences
Data Sequences: 342248
Test Sequences: 3330
Training Phases
Traceback (most recent call last):
  File "Train.py", line 141, in <module>
    train_batch = LoadBatches(train_indices)
  File "Train.py", line 56, in LoadBatches
    batch = utility.ReadBatchFromFile(DataFile, gather.flatten(), feature_dim)
  File "..\Library\Utility.py", line 185, in ReadBatchFromFile
    data[i] = np.float32(array.array('f', bytes))
ValueError: could not broadcast input array from shape (0) into shape (78)
`

**Comment by happyday521** [comment]
Same question. Have you figured it out?

**Comment by gillesroux** [comment]
The same happened to me and it turned out the `PyTorch/PAE/Dataset/Data.bin` file was invalid, weighing a few hundred bytes instead of a few MB. I downloaded the file again and it fixed the error.

**Comment by kotaxyz** [comment]
thanks mate i will try it and inform you 

> The same happened to me and it turned out the `PyTorch/PAE/Dataset/Data.bin` file was invalid, weighing a few hundred bytes instead of a few MB. I downloaded the file again and it fixed the error.

thanks mate i will try it out and inform you

**Comment by kotaxyz** [comment]
It worked thanks mate
