### ISSUE TITLE
SIG 2022: How to export MoCap data for training neural motion control?

### ISSUE THREAD

**Issue by happyday521** [sebastianstarke/AI4Animation#95]
Hi, thanks for your great work.

Can anyone tell me how to export MoCap data from the Unity project to train the neural motion controller(4.1)?  I didn't see the step guidance. In README,  "DeepPhasePipeline" seems only exports the training data for PAE, instead of the neural motion controller(4.1).

Thanks!

**Comment by pauzii** [comment]
Hi there, please have a look at the "Data Export for GNN" chapter in this tutorial; https://youtu.be/3ASGrxNDd0k
