### ISSUE TITLE
Porting animations to other engines

### ISSUE THREAD

**Issue by GeroVeni** [sebastianstarke/AI4Animation#96]
*This is probably not the right place to post this, but I am not sure where else to do so.*

I would like to try and port the animations to a different engine than Unity (e.g. Godot) but I am not sure where to start looking. Which is the main bit of code that translates the trained neural net to the actual skeletal animations ?

**Comment by arixlin** [comment]
You need to modify the actor.cs to align the bone order with the Demo.
