### ISSUE TITLE
2022 Unity Dance Demo: How to generate music feature files

### ISSUE THREAD

**Issue by arixlin** [sebastianstarke/AI4Animation#97]
Hi Sebastian,

I want to use other music to generate animations in Demo Dance, how do I generate feature files?   

Thanks!

**Comment by sebastianstarke** [comment]
I used the processing pipeline by the Transflower paper to generate music features, however, modified the format a little bit. I will look for the code I made for that and include it here if I find it, but the easiest way may be to generate your own music feature format using librosa and retrain the system.

**Comment by starryforest-ymxk** [comment]
I just did some work on this. If you still have this question, you can find it here : [DeepPhase-DanceGeneration](https://github.com/starryforest-ymxk/DeepPhase-DanceGeneration) Hope it help you. :) @arixlin
